language: php
sudo: false
php:
    - 5.5
    - 5.6
    - 7.0
    - nightly
matrix:
  fast_finish: true
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: nightly
before_install: "composer install"
script: "./vendor/bin/phpunit test"
