<?php
/**
 * CreateSubscriptionInvoice
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * CreateSubscriptionInvoice Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateSubscriptionInvoice implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'CreateSubscriptionInvoice';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'ref' => 'string',
        'instant' => 'bool',
        'due' => 'string',
        'plan_manual' => 'bool',
        'collect_additional_costs' => 'bool',
        'collect_credit' => 'bool',
        'apply_discounts' => 'bool',
        'order_lines' => '\Swagger\Client\Model\CreateOrderLine[]',
        'manual_transfer' => '\Swagger\Client\Model\ManualSettleTransfer'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'ref' => 'ref',
        'instant' => 'instant',
        'due' => 'due',
        'plan_manual' => 'plan_manual',
        'collect_additional_costs' => 'collect_additional_costs',
        'collect_credit' => 'collect_credit',
        'apply_discounts' => 'apply_discounts',
        'order_lines' => 'order_lines',
        'manual_transfer' => 'manual_transfer'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'ref' => 'setRef',
        'instant' => 'setInstant',
        'due' => 'setDue',
        'plan_manual' => 'setPlanManual',
        'collect_additional_costs' => 'setCollectAdditionalCosts',
        'collect_credit' => 'setCollectCredit',
        'apply_discounts' => 'setApplyDiscounts',
        'order_lines' => 'setOrderLines',
        'manual_transfer' => 'setManualTransfer'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'ref' => 'getRef',
        'instant' => 'getInstant',
        'due' => 'getDue',
        'plan_manual' => 'getPlanManual',
        'collect_additional_costs' => 'getCollectAdditionalCosts',
        'collect_credit' => 'getCollectCredit',
        'apply_discounts' => 'getApplyDiscounts',
        'order_lines' => 'getOrderLines',
        'manual_transfer' => 'getManualTransfer'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ref'] = isset($data['ref']) ? $data['ref'] : null;
        $this->container['instant'] = isset($data['instant']) ? $data['instant'] : false;
        $this->container['due'] = isset($data['due']) ? $data['due'] : null;
        $this->container['plan_manual'] = isset($data['plan_manual']) ? $data['plan_manual'] : false;
        $this->container['collect_additional_costs'] = isset($data['collect_additional_costs']) ? $data['collect_additional_costs'] : false;
        $this->container['collect_credit'] = isset($data['collect_credit']) ? $data['collect_credit'] : false;
        $this->container['apply_discounts'] = isset($data['apply_discounts']) ? $data['apply_discounts'] : false;
        $this->container['order_lines'] = isset($data['order_lines']) ? $data['order_lines'] : null;
        $this->container['manual_transfer'] = isset($data['manual_transfer']) ? $data['manual_transfer'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets ref
     * @return string
     */
    public function getRef()
    {
        return $this->container['ref'];
    }

    /**
     * Sets ref
     * @param string $ref Optional reference to avoid double creations. Only one invoice can be created per reference.
     * @return $this
     */
    public function setRef($ref)
    {
        $this->container['ref'] = $ref;

        return $this;
    }

    /**
     * Gets instant
     * @return bool
     */
    public function getInstant()
    {
        return $this->container['instant'];
    }

    /**
     * Sets instant
     * @param bool $instant Create and process transaction instantly and only create invoice for successful transaction (default false)
     * @return $this
     */
    public function setInstant($instant)
    {
        $this->container['instant'] = $instant;

        return $this;
    }

    /**
     * Gets due
     * @return string
     */
    public function getDue()
    {
        return $this->container['due'];
    }

    /**
     * Sets due
     * @param string $due Optional due date and time on the form yyyy-MM-dd, yyyyMMdd, yyyy-MM-ddTHH:mm and yyyy-MM-ddTHH:mm:ss from which the invoice is eligible to be collected
     * @return $this
     */
    public function setDue($due)
    {
        $this->container['due'] = $due;

        return $this;
    }

    /**
     * Gets plan_manual
     * @return bool
     */
    public function getPlanManual()
    {
        return $this->container['plan_manual'];
    }

    /**
     * Sets plan_manual
     * @param bool $plan_manual Create manually for plan by adding plan product as orderline (default false)
     * @return $this
     */
    public function setPlanManual($plan_manual)
    {
        $this->container['plan_manual'] = $plan_manual;

        return $this;
    }

    /**
     * Gets collect_additional_costs
     * @return bool
     */
    public function getCollectAdditionalCosts()
    {
        return $this->container['collect_additional_costs'];
    }

    /**
     * Sets collect_additional_costs
     * @param bool $collect_additional_costs Collect pending additional costs and transfer to invoice (default true)
     * @return $this
     */
    public function setCollectAdditionalCosts($collect_additional_costs)
    {
        $this->container['collect_additional_costs'] = $collect_additional_costs;

        return $this;
    }

    /**
     * Gets collect_credit
     * @return bool
     */
    public function getCollectCredit()
    {
        return $this->container['collect_credit'];
    }

    /**
     * Sets collect_credit
     * @param bool $collect_credit Collect pending credit and transfer to invoice (default true)
     * @return $this
     */
    public function setCollectCredit($collect_credit)
    {
        $this->container['collect_credit'] = $collect_credit;

        return $this;
    }

    /**
     * Gets apply_discounts
     * @return bool
     */
    public function getApplyDiscounts()
    {
        return $this->container['apply_discounts'];
    }

    /**
     * Sets apply_discounts
     * @param bool $apply_discounts Apply potential discounts for the subscription to the invoice order lines (default true)
     * @return $this
     */
    public function setApplyDiscounts($apply_discounts)
    {
        $this->container['apply_discounts'] = $apply_discounts;

        return $this;
    }

    /**
     * Gets order_lines
     * @return \Swagger\Client\Model\CreateOrderLine[]
     */
    public function getOrderLines()
    {
        return $this->container['order_lines'];
    }

    /**
     * Sets order_lines
     * @param \Swagger\Client\Model\CreateOrderLine[] $order_lines Optional orderlines for the invoice
     * @return $this
     */
    public function setOrderLines($order_lines)
    {
        $this->container['order_lines'] = $order_lines;

        return $this;
    }

    /**
     * Gets manual_transfer
     * @return \Swagger\Client\Model\ManualSettleTransfer
     */
    public function getManualTransfer()
    {
        return $this->container['manual_transfer'];
    }

    /**
     * Sets manual_transfer
     * @param \Swagger\Client\Model\ManualSettleTransfer $manual_transfer Optional manual tranfer. If given the invoice will be settled using the manual transfer transaction.
     * @return $this
     */
    public function setManualTransfer($manual_transfer)
    {
        $this->container['manual_transfer'] = $manual_transfer;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


