<?php
/**
 * InvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvoiceTest Class Doc Comment
 *
 * @category    Class */
// * @description Invoice
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Invoice"
     */
    public function testInvoice()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {

    }

    /**
     * Test attribute "subscription"
     */
    public function testPropertySubscription()
    {

    }

    /**
     * Test attribute "plan"
     */
    public function testPropertyPlan()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {

    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "due"
     */
    public function testPropertyDue()
    {

    }

    /**
     * Test attribute "failed"
     */
    public function testPropertyFailed()
    {

    }

    /**
     * Test attribute "settled"
     */
    public function testPropertySettled()
    {

    }

    /**
     * Test attribute "cancelled"
     */
    public function testPropertyCancelled()
    {

    }

    /**
     * Test attribute "credits"
     */
    public function testPropertyCredits()
    {

    }

    /**
     * Test attribute "adjustments"
     */
    public function testPropertyAdjustments()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "plan_version"
     */
    public function testPropertyPlanVersion()
    {

    }

    /**
     * Test attribute "dunning_plan"
     */
    public function testPropertyDunningPlan()
    {

    }

    /**
     * Test attribute "discount_amount"
     */
    public function testPropertyDiscountAmount()
    {

    }

    /**
     * Test attribute "org_amount"
     */
    public function testPropertyOrgAmount()
    {

    }

    /**
     * Test attribute "amount_vat"
     */
    public function testPropertyAmountVat()
    {

    }

    /**
     * Test attribute "amount_ex_vat"
     */
    public function testPropertyAmountExVat()
    {

    }

    /**
     * Test attribute "settled_amount"
     */
    public function testPropertySettledAmount()
    {

    }

    /**
     * Test attribute "refunded_amount"
     */
    public function testPropertyRefundedAmount()
    {

    }

    /**
     * Test attribute "period_number"
     */
    public function testPropertyPeriodNumber()
    {

    }

    /**
     * Test attribute "order_lines"
     */
    public function testPropertyOrderLines()
    {

    }

    /**
     * Test attribute "additional_costs"
     */
    public function testPropertyAdditionalCosts()
    {

    }

    /**
     * Test attribute "card_transactions"
     */
    public function testPropertyCardTransactions()
    {

    }

    /**
     * Test attribute "manual_transactions"
     */
    public function testPropertyManualTransactions()
    {

    }

    /**
     * Test attribute "credit_notes"
     */
    public function testPropertyCreditNotes()
    {

    }

    /**
     * Test attribute "dunning_start"
     */
    public function testPropertyDunningStart()
    {

    }

    /**
     * Test attribute "dunning_count"
     */
    public function testPropertyDunningCount()
    {

    }

    /**
     * Test attribute "dunning_expired"
     */
    public function testPropertyDunningExpired()
    {

    }

    /**
     * Test attribute "period_from"
     */
    public function testPropertyPeriodFrom()
    {

    }

    /**
     * Test attribute "period_to"
     */
    public function testPropertyPeriodTo()
    {

    }

}
