<?php
/**
 * SubscriptionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SubscriptionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for cancelChangePlan
     *
     * Cancel pending plan change.
     *
     */
    public function testCancelChangePlan()
    {

    }

    /**
     * Test case for cancelSubscription
     *
     * Cancel subscription.
     *
     */
    public function testCancelSubscription()
    {

    }

    /**
     * Test case for changeNextPeriodStartJson
     *
     * Change next renewal date.
     *
     */
    public function testChangeNextPeriodStartJson()
    {

    }

    /**
     * Test case for changePlanJson
     *
     * Change plan.
     *
     */
    public function testChangePlanJson()
    {

    }

    /**
     * Test case for createSubscriptionDiscount
     *
     * Add subscription discount.
     *
     */
    public function testCreateSubscriptionDiscount()
    {

    }

    /**
     * Test case for createSubscriptionInvoice
     *
     * Create invoice ondemand for subscription.
     *
     */
    public function testCreateSubscriptionInvoice()
    {

    }

    /**
     * Test case for createSubscriptionJson
     *
     * Create subscription.
     *
     */
    public function testCreateSubscriptionJson()
    {

    }

    /**
     * Test case for deleteSubscriptionDiscount
     *
     * Delete subscription discount.
     *
     */
    public function testDeleteSubscriptionDiscount()
    {

    }

    /**
     * Test case for expire
     *
     * Expire subscription.
     *
     */
    public function testExpire()
    {

    }

    /**
     * Test case for getSubscription
     *
     * Get subscription.
     *
     */
    public function testGetSubscription()
    {

    }

    /**
     * Test case for getSubscriptionDiscount
     *
     * Get subscription discount.
     *
     */
    public function testGetSubscriptionDiscount()
    {

    }

    /**
     * Test case for getSubscriptionDiscounts
     *
     * Get subscription discounts.
     *
     */
    public function testGetSubscriptionDiscounts()
    {

    }

    /**
     * Test case for getSubscriptionPaymentMethods
     *
     * Get payment methods.
     *
     */
    public function testGetSubscriptionPaymentMethods()
    {

    }

    /**
     * Test case for getSubscriptions
     *
     * Get list of subscriptions.
     *
     */
    public function testGetSubscriptions()
    {

    }

    /**
     * Test case for intervalAmount
     *
     * Calculate interval amount.
     *
     */
    public function testIntervalAmount()
    {

    }

    /**
     * Test case for removeAllPaymentMethods
     *
     * Remove all payment methods.
     *
     */
    public function testRemoveAllPaymentMethods()
    {

    }

    /**
     * Test case for removePaymentMethod
     *
     * Remove payment method.
     *
     */
    public function testRemovePaymentMethod()
    {

    }

    /**
     * Test case for setCardPaymentMethodJson
     *
     * Set card payment method.
     *
     */
    public function testSetCardPaymentMethodJson()
    {

    }

    /**
     * Test case for uncancel
     *
     * Uncancel subscription.
     *
     */
    public function testUncancel()
    {

    }

}
